### PR TITLE
Mock up view all

### PR DESCRIPTION
**Pull request by surajp28**

### CODE REVIEW

**Review by ayishacs — DISMISSED** [review]
Icon sizes for sharing, uploading and downloading are not in accordance with the font size of the application and other textual data in the page. The font style of the text should have a uniform and clean appearance.

**Comment by surajp28** [comment]
The changes have been made.Kindly approve

**Comment by ayishacs** [comment]
Appreciated

**Comment by ayishacs** [comment]
Approving the request.

**Comment by ayishacs** [comment]
Merging the pull request

**Review by visheshdembla — APPROVED** [review]

**Comment by surajp28** [comment]
Hello @visheshdembla @ayishacs 
This still isnt allowing me to merge. It says merging is blocked and can only be performed once the requested changes are addressed.

**Comment by surajp28** [comment]
https://github.com/airavata-courses/Panorama/tree/mockup-login/res/imgs/milestone-1

**Pull request merged**
