### PR TITLE
Signup mockup

### PR DESCRIPTION
**Pull request by surajp28**

### CODE REVIEW

**Review by ayishacs — DISMISSED** [review]
The text for inputs is not properly aligned in the centre. It should either be placed exactly in the centre or rightmost side. And there is a need to add the application name and at least 1 or 2 lines description of Panorama on this page.

**Comment by surajp28** [comment]
Would it be better if we did the Panorama name and description on the login page? And the sign up page would be more like a pop-up?

**Comment by ayishacs** [comment]
Either way it works but the alignment isn’t uniform

**Comment by surajp28** [comment]
@ayishacs @visheshdembla The changes have been made. Can yall review it and approve the P.R?

**Review by visheshdembla — APPROVED** [review]
Seems fine to me

**Pull request merged**
