### PR TITLE
login-mockup

### PR DESCRIPTION
**Pull request by surajp28**

### CODE REVIEW

**Review by ayishacs — DISMISSED** [review]
Remove multiple "OR's" and add the following text below login button - 
OR 
Sign Up Using
Icons for IU, GMAIL and so on

**Comment by surajp28** [comment]
I had a question w.r.t the suggestion. If I use sign-up using the icons, doesn't that indicate a direct sign in?

**Comment by surajp28** [comment]
Hi @ayishacs @visheshdembla 
The changes have been updated

**Comment by ayishacs** [comment]
Hi Suraj, If changes were implemented, could you please share the link for the same. So that, I can approve the pull request and merge the changes
@surajp28

**Review by visheshdembla — APPROVED** [review]

**Comment by surajp28** [comment]
Hello @ayishacs @visheshdembla ,
This isnt allowing me to merge as the requested changes arent addressed yet.

**Comment by surajp28** [comment]
https://github.com/airavata-courses/Panorama/tree/mockup-login/res/imgs/milestone-1

**Comment by visheshdembla** [comment]
you can merge now I dismissed the pendign review

**Pull request merged**
