### PR TITLE
#1 Updated napkin diagram in README.md

### LINKED ISSUE #1: create napkin diagram in README
@visheshdembla @surajp28 @ayishacs  
#First deliverable
Task1: Napkin diagram

### PR DESCRIPTION
**Pull request by ayishacs**
Updated readme with napkin diagram. Please review and merge the changes.

### CODE REVIEW

**Comment by visheshdembla** [comment]
changed PR base branch to dev as main would only be used for Release Milestones.

**Review by smarru — COMMENTED** [review]
This is a good figure, you guys seem to have captured the "user-centric" perspective very well. It is telling you your system will enable users to cloud storage and download from cloud storage.  Are you guys only planing on this capability or anything more? If so I suggest you capture other planned capabilities as well. Be ambitous.

**Comment by ayishacs** [comment]
> This is a good figure, you guys seem to have captured the "user-centric" perspective very well. It is telling you your system will enable users to cloud storage and download from cloud storage. Are you guys only planing on this capability or anything more? If so I suggest you capture other planned capabilities as well. Be ambitous.


@smarru 
Thank you for your valuable feedback Professor Suresh, We will definitely work on including extended capabilities as we progress.

**Review by visheshdembla — APPROVED** [review]
approved with minor changes that were discussed during review of the diagram

**Pull request merged**
